spring:
  application:
    name: service
  jackson:
    deserialization:
      accept-float-as-int: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          client-id: 327412969757-019g36m3vm2jnij0n9got6ipre8vmuij.apps.googleusercontent.com


server:
  port: 8085
  servlet:
    context-path: /tvn-service
  error:
    include-message: always
  forward-headers-strategy: native